name: "Inverter 11k Modbus Add-on"
description: "Read Inverter data via Modbus and publish it to HA via MQTT"
version: "1.0.0-beta1"
slug: "inverter_11k_modbus_add-on"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
host_network: true
watchdog: "http://[HOST]:8082/health"
uart: true
usb: true
hassio_api: true
homeassistant_api: false
services:
  - mqtt:need
panel_icon: "mdi:cable-data"
options:
  serial_interface: "/dev/ttyUSB0"
  mqtt_topic: "inverter_11k"
  mqtt_update_interval: 1
  modbus_id: 1
  enable_ha_discovery: true
  ha_discovery_prefix: "homeassistant"
  invert_ha_dis_charge_measurements: false
  logging_level: "info"
schema:
  serial_interface: "str"
  mqtt_topic: "str"
  mqtt_update_interval: "int"
  modbus_id: "int"
  enable_ha_discovery: "bool"
  ha_discovery_prefix: "str"
  invert_ha_dis_charge_measurements: "bool"
  logging_level: "list(info|error|debug)"
